### ISSUE TITLE
No List Create/Basic Call Errors

### ISSUE THREAD

**Issue by sheyworth** [skovmand/mailchimp-laravel#25]
Hi there,

I love your package. With that being said, I do not see to post/create a list in Lists.php.

When I try to manually use your mailchimp package

`$createList = $mailchimp->call('lists', $input);`

The error I receive is:
No method '/lists' found

What is my issue and what can I do to work around this? Or do I have to extend your package to allow for POST functions?

**Comment by skovmand** [comment]
Hi sheyworth. 

My package is really only a way to instantiate the Mailchimp V2 PHP Client, so the problem would be with them. So checkout their package: https://bitbucket.org/mailchimp/mailchimp-api-php.git

But do beware that it uses version 2 of the Mailchimp API, which is deprecated since jan 1, 2017.


I hope you can find a solution!
