### ISSUE TITLE
cant install in composer

### ISSUE THREAD

**Issue by webineh** [skovmand/mailchimp-laravel#33]
hello it cant install in composer , it connect bitbucket verstion  control

**Comment by skovmand** [comment]
Hi Vahid.

Sorry for the late reply.

I don't think the error you are describing has to do with this package.
This repository has nothing to do with Bitbucket.

I hope you will find a solution.

Regards, Niels.

**Comment by webineh** [comment]
oh . but i cant install it .

**Comment by dewwwald** [comment]
@vahidalvandi consider the amount  of users that use this lib and that you are only one. If you are the only one experiencing it then surely the issue must be something you did. 

Now that I have your attention... I don't mean to be rude but I want you to understand the problem here. You did not provide any debugging information at all. No error messages, no reproduction steps, not even a link to a public repo that reproduces the issue. In order to get better assistance you must provide at least one of the above mentioned.
